### ISSUE TITLE
build monolithic `lodash` to depend on `lodash.*` modules

### ISSUE THREAD

**Issue by ahdinosaur** [lodash/lodash-cli#44]
hey,

first, [thank you for making lodash so modular](https://github.com/lodash/lodash-cli/issues/25). i really appreciate using `lodash.*` modules in my projects, it's [great](https://blog.andyet.com/2015/03/25/amped-down).

the only part that's slightly less awesome is trying to use modules from other authors who prefer to depend on the internal modules in the monolithic `lodash` instead of `lodash.*` modules, e.g. [a recent pull request i made to 'gajus/canonical'](https://github.com/gajus/canonical/pull/1).

> @gajus: if lodash main package did not come as a bundle of all functions and instead had each of them as a "dependency", then your proposal to use lodash.* packages would indeed make sense because a bundler would almost always recognise the duplication.

i'm making an issue here because i think that's an elegant way to achieve module nirvana (developers can use either `lodash.*` modules or internal modules in the monolithic `lodash` and bundlers would see them as being equivalent) so i'm curious your thoughts @jdalton on whether this could be a change you'd support in `lodash`.

cheers :shell:

**Comment by gajus** [comment]
Furthermore, this would be a non-breaking change. Could be applied as a minor version bump.

**Comment by jdalton** [comment]
We could have the modules in the `lodash` package point to `lodash.*`  package but I think that would cause other problems.

In v2 when I introduced `lodash.*` packages I got a lot of push back on the number of dependencies each had. It was too modular and folks wouldn't use them. They wanted a self contained packages with few dependencies. In order to reduce dep graphs (deps or deps) in v3 I had to implement inlining for the `lodash.*` packages. This means several of the smaller packages are inlined directly in the source of the `lodash.*` packages instead of taking a dependency on them. This means a minor bit of code duplication.

Making `lodash` depend on 200+ packages would upset a lot of folks because lodash is depended on in some way by ~25% of npm packages. I could imagine their install times and disc usage would increase significantly as it went from 0 to 200+ dependencies.

**Comment by ahdinosaur** [comment]
was worth a try. :wink: thanks for the response. :cherry_blossom:

**Comment by gajus** [comment]
> I would imagine their install times and disc usage would increase significantly as it went from 0 to 200+ dependencies.

@jdalton I don't agree.

Here is a test subject (a module that has each lodash module as a dependency):

```bash
npm install lodash-modularized
```

Installation time:

Installation time is affected only the first time. On a 3g connection, it takes about 30 seconds the first time. The second time, npm will use cache. It takes just 3 seconds. The cache is system wide. Cache is per module per version. Therefore, releasing new version of any lodash module will de-cache only that particular module.

Disk size:

The entire `lodash-modularized` module size is 3M. The size is negligible in the context of the modern hardware.

**Comment by gajus** [comment]
The modularisation at the moment is a mess. People who use `lodash.*` packages lose because they cannot benefit from de-duplication if any of the project dependencies use `lodash`. People who use `lodash` modularly (loading just module files, e.g. `lodash/lang/isArray`) lose if dependencies use `lodash.*` modules.

**Comment by jdalton** [comment]
> Here is a test subject

You're missing about 63 packages. Then account for the added delay and download to 25% of the packages on npm.

> The modularisation at the moment is a mess:

If that's your thing don't use the `lodash.*` packages.

**Comment by gajus** [comment]
I don't understand the mindset "my package is a dependency of X number of packages therefore it has to behave in Y way". However, I never had to maintain a package that popular.

**Comment by jdalton** [comment]
> I don't understand the mindset "my package is a dependency of X number of packages therefore it has to behave in Y way".

That was just 63 missing for v3, v4 adds another ~30 for total of ~224 (not counting internal deps). As times goes on more and more methods will be added to the kitchen sink and the deps would continue to grow. Having them as deps won't scale well. We got quite a lot of push back for packages having 8 or 10 dependencies in v2 I can't imagine the kind of backlash that we'd receive from 200+.

Thankfully as it stands there hasn't been a large problem with mixing `lodash.*` and `lodash/*` packages and they satisfy strong dev preference for one or the other.

**Comment by gajus** [comment]
I don't understand the logic for promoting two different methods of using lodash modularly that do not mix well with each other. Everyone would benefit if lodash would be a single package. Developers wishing to use individual modules without importing the entire codebase could continue to do that importing lodash/*/* files that in turn resolve internal dependencies. Lazy (frontend) developers can proceed to load the entire package.

Is that not enough argument against having lodash.* packages? What was the original reasoning for introducing then in the first place?

**Comment by jdalton** [comment]
> I don't understand the logic for promoting two different methods of using lodash modularly that do not mix well with each other.

The different approaches came from devs straight up refusing to use one over the other. So since devs have strong opinions and we'd like adoption from Ember, amp, redux, react, and others we have packages and builds that satisfy their preferences.

> Is that not enough argument against having lodash.* packages? What was the original reasoning for introducing then in the first place?

The `lodash.*` packages were our first offering in the modularized space. Going forward in v4 I can deprecate the `lodash.*` and encourage use of `lodash/*` modules.

**Comment by jdalton** [comment]
@gajus I may be able to reverse your suggestion and keep `lodash` as it is but make all `lodash.*` packages dep `lodash` and then point to their `lodash/xy/z` paths.

**Comment by jdalton** [comment]
We'll be able to address this once npm@3 goes stable as it will auto hoist deps so even if a package has `lodash.foo` and `lodash.bar` the dep `lodash` will be downloaded once.

**Comment by gajus** [comment]
Amazing.

**Comment by jdalton** [comment]
\cc @othiym23 @phated

**Comment by jdalton** [comment]
Forrest would this also be doable in a pre-3.0 world with npm cache? Like it would hit the first `lodash` package download, cache it, then all subsequent requests would hit the cached version?

**Comment by jdalton** [comment]
Do you see a glaring down side to this approach?

**Comment by jdalton** [comment]
One issue here is that `lodash.*` are independently versioned so I could see a situation where one package would depend on an older `lodash` version and so downloading multiple `lodash` packages (:barf:)

**Comment by ahdinosaur** [comment]
> I may be able to reverse your suggestion and keep lodash as it is but make all lodash.* packages depend on lodash and then point to their lodash/xy/z paths. Cred to @alxlu for the suggestion.

works for me. :smile: 

> The lodash.* packages were our first offering in the modularized space. Going forward, in v4, I could deprecate the lodash.* packages and encourage use of lodash/* modules.

i'd still prefer `lodash.*` over `lodash/*` as `lodash/*` locks you in to a single major version of `lodash`, so an upgrade has to be done all at once, as opposed to being able to track and upgrade your `lodash.*` versions one-by-one.

> One issue here is that lodash.* are independently versioned so I could see a situation where one package would depend on an older lodash version and so download multiple lodash packages (:barf:)

i'm not sure what the problem here is, as while you'd download a `lodash` for every major version your `lodash.*` modules are using (at most a few), you would only `require` in the specific functions you're using from each version. or am i missing something?

**Comment by jdalton** [comment]
> i'm not sure what the problem here is, as while you'd download a lodash for every major version 

It wouldn't be for every major version if the packages are to be independently versioned they'd map to minor or patch version of lodash. So you could have `lodash.cloneDeep` that depends on `lodash` v4.0.3 but `lodash.merge` that depends on `lodash` v4.1.0.

**Comment by jdalton** [comment]
That same gotcha could be applied to `lodash` consuming the `lodash.*` packages too as each version may require a minor/patch version of a `lodash.*` package making no guarantee that they could avoid duplication in bundles any better than today.

**Comment by ahdinosaur** [comment]
> > i'm not sure what the problem here is, as while you'd download a lodash for every major version
>
> It wouldn't be for every major version if the packages are to be independently versioned they'd map to minor or patch version of lodash. So you could have lodash.cloneDeep that depends on lodash v4.0.3 but lodash.merge that depends on lodash v4.1.0.

yeah, that makes sense, was about to correct myself. it's not ideal but i think you're right that us `lodash.*` users are more willing to put up with the duplication if it means de-duplication with `lodash` users and giving us control of per-module versions. it'd be interesting to see how it ends up in practice and whether that would be enough of a pain.

**Comment by jdalton** [comment]
That same gotcha could be applied to `lodash` consuming the `lodash.*` packages too as each version may require a minor/patch version of a `lodash.*` package making no guarantee that they could avoid duplication in bundles any better than today.

**Comment by othiym23** [comment]
The npm _cache_ is mostly unchanged between `npm@2` and `npm@3` -- it will download it the first time, and after that each install only takes as long as it takes to unpack the package tarball into place (for a given version). That unpacking takes a nontrivial amount of time, so the automatic deduping of `npm@3` will make a significant difference here

One thing to keep in mind about the npm _installer_ is that with `npm@2`, it just looks at the top-level packages, and if they're all there and match the semver in `package.json`, the installer calls that good enough and doesn't do anything further. With `npm@3`, because it has to realize the entire tree before figuring out what actions to apply, having lots of little packages involved will significantly slow down the install process. I _think_ that's an argument in favor of the approach you've outlined, @jdalton, but this is something that changes how long installs take, sometimes in unpleasantly surprising ways.

**Comment by jdalton** [comment]
@othiym23 it sounds like it's a you're darned if you do and darned if you don't situations : )

**Comment by othiym23** [comment]
@jdalton is your presumption that `lodash.*` would have a pinned dependency on the same version of `lodash`? I can see why you'd want that (we're nuking npm's API documentation because we don't make any commitments to the stability of npm's internal APIs), but if you could make it so that you could just `^`-depend between the two, that would make the risk of unnecessary duplication considerably.

**Comment by othiym23** [comment]
The emphasis in `npm@3` up until now has mostly been on making the install process correct and robust in as many situations as possible. In the near term, @iarna's attention is going to shift to improving npm's performance, so with any luck this will be a transitory caveat.

**Comment by jdalton** [comment]
> is your presumption that `lodash.*` would have a pinned dependency on the same version of `lodash`?

I'm trying to brainstorm a way to have `lodash/foo/bar` and `lodash.*` share dependencies so bundles that mix the two can avoid duplication. I don't think having `lodash` depend on hundreds of modules is practical but having the opposite `lodash.*` could run into having to download multiple versions of the kitchen sink `lodash` (also not great). Both approaches would require pinned dep versions to allow independent versioning and no funny business when devs lock to a specific `lodash` version dep.

There may not be a good way to reconcile the two styles (`lodash/foo/bar` and `lodash.bar`).

**Comment by jdalton** [comment]
On thinking on this a bit more I want to expand on my over simplified comment
> since devs have strong opinions

I think these two builds, `lodash/foo/bar` and `lodash.*`, have different advantages and cater to different needs.

`lodash/foo/bar` is great for devs who are already using the `lodash` package but want to create smaller bundles. They're already OK with having all methods associated with the version of `lodash` they depend on.

`lodash.*` is for devs who may not be using `lodash` already and want a handful of methods. Those methods may be different versions and have functionality that's version dependent.

With that I think it's ok to offer both even if they don't mesh well together (which is understandable).

**Comment by ahdinosaur** [comment]
@AmpersandJS, any thoughts on this? curious since y'all are advocates of `lodash.*` (previously `amp-*`) modules, which is what changed my mind to want more modular utilities as well.
